<?php
/**
 * Created by PhpStorm.
 * User: Vladymir
 * Date: 31.08.2016
 * Time: 10:48
 */

namespace app\models;
use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
  public static function tableName()
  {
      return 'category'; // TODO: Change the autogenerated stub
  }


    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['category_id' => 'id' ]);
    }

}